# Generated by Django 5.0.7 on 2024-09-23 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Firereport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=250, null=True)),
                ('MobileNumber', models.CharField(max_length=12, null=True)),
                ('Location', models.CharField(max_length=200, null=True)),
                ('Message', models.CharField(max_length=200, null=True)),
                ('Status', models.CharField(max_length=150, null=True)),
                ('Postingdate', models.DateTimeField(auto_now_add=True)),
                ('AssignedTime', models.CharField(max_length=150, null=True)),
                ('UpdationDate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=200, null=True)),
                ('teamLeaderName', models.CharField(max_length=250, null=True)),
                ('teamLeadMobno', models.CharField(max_length=15, null=True)),
                ('teamMembers', models.CharField(max_length=300, null=True)),
                ('postingDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firetequesthistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('remark', models.CharField(max_length=250, null=True)),
                ('postingDate', models.DateTimeField(auto_now_add=True)),
                ('firereport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firereport.firereport')),
            ],
        ),
        migrations.AddField(
            model_name='firereport',
            name='AssignTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firereport.teams'),
        ),
    ]
